test on iPhone 15 instead of 16
iPhone 16 fails consistently with a 500

```
Response Status Code: 13
Response Message:
    Appium error: An unknown server-side error occurred while processing the command. Original error: window._webdriver_manualPoll is not a function. (In 'window._webdriver_manualPoll()', 'window._webdriver_manualPoll' is undefined)
Error: Unexpected HTTP status: 500 Internal Server Error
```