Dojo AMD module.uri is server relative. browserModuleLocation could not handle this. Added a test case, and expect to the test, to catch this. And fixed the shortcoming.
On Mac:
Mocha IDEA and console test node ok.
Intern IDEA and console test node ok.
Mocha Web test  ok for Chrome, Safari. 3 expected failures on FF (see below, waiting for FF 53).
Intern Web test ok for Chrome. 3 expected failures on FF (but 5 times clicking “wait”).

Intern Web test on Safari fails:
Fatal error during pre-execution stage
Error: Cannot find the Node.js require
  at <contracts/node_modules/intern/browser_modules/dojo/node.js:14:24>
  at execModule  <contracts/node_modules/intern/browser_modules/dojo/loader.js:332:67>
  at <contracts/node_modules/intern/browser_modules/dojo/loader.js:374:31>
  at guardCheckComplete  <contracts/node_modules/intern/browser_modules/dojo/loader.js:361:13>
  at checkComplete  <contracts/node_modules/intern/browser_modules/dojo/loader.js:366:50>
  at onLoadCallback  <contracts/node_modules/intern/browser_modules/dojo/loader.js:428:30>
  at handler  <contracts/node_modules/intern/browser_modules/dojo/loader.js:514:73>