Trying to get some results from Browserstack. First result. This will turn out to be difficult.
First remark is that this is slow.
I did some experiments, and found it difficult to get anything to work. The FF / WIN 8 combination started ok, but failed because we get the “wait” button, and there is no way to continue. Although the “53 beta” version of the browser was specified, v52 was run. The specs don’t support WIN10 (but this was reported to run on 8.1).
Trying Chrome, started the test. This is committed. Failed with 7 errors (below). These errors are in the test: these remote tests run from localhost:9000, while the test expects something else.

Some other combinations in this file using os and os_version were tried, but failed, with “incompatible browser / os combination”, although they are documented.
This will turn out to be a hunt and peck endeavour.

The 7 errors:

× chrome 57 on WIN8 - unit tests - _private/util - #stackOutsideThisLibrary - only has stack lines outside the library, and the first line refers to this code, for a local error
AssertionError: expected '    at registerSuite (http://localhost:9000/__intern/lib/interfaces/tdd.js:17:11)' to satisfy [Function]
  at Assertion.satisfy  <__intern/browser_modules/chai/chai.js:1761:10>
  at Assertion.ctx.(anonymous function) [as satisfy]  <__intern/browser_modules/chai/chai.js:4192:25>
  at <test/_private/utilTest.js:555:31>
  at Array.forEach  <native>
  at Test.test  <test/_private/utilTest.js:544:24>
  at <__intern/lib/Test.js:191:24>
  at <__intern/browser_modules/dojo/Promise.js:156:41>
  at runCallbacks  <__intern/browser_modules/dojo/Promise.js:19:22>
  at <__intern/browser_modules/dojo/Promise.js:103:21>
  at run  <__intern/browser_modules/dojo/Promise.js:51:33>
× chrome 57 on WIN8 - unit tests - _private/util - #browserModuleLocation - returns a sensible result with AMD module URI "simple.js"
AssertionError: expected 'http://localhost:9000/__intern/simple.js' to match /^http:\/\/localhost:63342/
  at Assertion.assertMatch  <__intern/browser_modules/chai/chai.js:1363:10>
  at Assertion.ctx.(anonymous function) [as match]  <__intern/browser_modules/chai/chai.js:4192:25>
  at Test.test  <test/_private/utilTest.js:750:31>
  at <__intern/lib/Test.js:191:24>
  at <__intern/browser_modules/dojo/Promise.js:156:41>
  at runCallbacks  <__intern/browser_modules/dojo/Promise.js:19:22>
  at <__intern/browser_modules/dojo/Promise.js:103:21>
  at run  <__intern/browser_modules/dojo/Promise.js:51:33>
  at CallbackQueue.drain  <__intern/browser_modules/dojo/CallbackQueue.js:39:35>
  at MutationObserver.<anonymous>  <__intern/browser_modules/dojo/nextTick.js:52:27>
× chrome 57 on WIN8 - unit tests - _private/util - #browserModuleLocation - returns a sensible result with AMD module URI "./peer.js"
AssertionError: expected 'http://localhost:9000/__intern/peer.js' to match /^http:\/\/localhost:63342/
  at Assertion.assertMatch  <__intern/browser_modules/chai/chai.js:1363:10>
  at Assertion.ctx.(anonymous function) [as match]  <__intern/browser_modules/chai/chai.js:4192:25>
  at Test.test  <test/_private/utilTest.js:750:31>
  at <__intern/lib/Test.js:191:24>
  at <__intern/browser_modules/dojo/Promise.js:156:41>
  at runCallbacks  <__intern/browser_modules/dojo/Promise.js:19:22>
  at <__intern/browser_modules/dojo/Promise.js:103:21>
  at run  <__intern/browser_modules/dojo/Promise.js:51:33>
  at CallbackQueue.drain  <__intern/browser_modules/dojo/CallbackQueue.js:39:35>
  at MutationObserver.<anonymous>  <__intern/browser_modules/dojo/nextTick.js:52:27>
× chrome 57 on WIN8 - unit tests - _private/util - #browserModuleLocation - returns a sensible result with AMD module URI "./dir/dir/deep.js"
AssertionError: expected 'http://localhost:9000/__intern/dir/dir/deep.js' to match /^http:\/\/localhost:63342/
  at Assertion.assertMatch  <__intern/browser_modules/chai/chai.js:1363:10>
  at Assertion.ctx.(anonymous function) [as match]  <__intern/browser_modules/chai/chai.js:4192:25>
  at Test.test  <test/_private/utilTest.js:750:31>
  at <__intern/lib/Test.js:191:24>
  at <__intern/browser_modules/dojo/Promise.js:156:41>
  at runCallbacks  <__intern/browser_modules/dojo/Promise.js:19:22>
  at <__intern/browser_modules/dojo/Promise.js:103:21>
  at run  <__intern/browser_modules/dojo/Promise.js:51:33>
  at CallbackQueue.drain  <__intern/browser_modules/dojo/CallbackQueue.js:39:35>
  at MutationObserver.<anonymous>  <__intern/browser_modules/dojo/nextTick.js:52:27>
× chrome 57 on WIN8 - unit tests - _private/util - #browserModuleLocation - returns a sensible result with AMD module URI "../../down/down/other.js"
AssertionError: expected 'http://down/down/other.js' to match /^http:\/\/localhost:63342/
  at Assertion.assertMatch  <__intern/browser_modules/chai/chai.js:1363:10>
  at Assertion.ctx.(anonymous function) [as match]  <__intern/browser_modules/chai/chai.js:4192:25>
  at Test.test  <test/_private/utilTest.js:750:31>
  at <__intern/lib/Test.js:191:24>
  at <__intern/browser_modules/dojo/Promise.js:156:41>
  at runCallbacks  <__intern/browser_modules/dojo/Promise.js:19:22>
  at <__intern/browser_modules/dojo/Promise.js:103:21>
  at run  <__intern/browser_modules/dojo/Promise.js:51:33>
  at CallbackQueue.drain  <__intern/browser_modules/dojo/CallbackQueue.js:39:35>
  at MutationObserver.<anonymous>  <__intern/browser_modules/dojo/nextTick.js:52:27>
× chrome 57 on WIN8 - unit tests - _private/util - #browserModuleLocation - returns a sensible result with AMD module URI "./../.././down/down/../../down/./complex.js"
AssertionError: expected 'http://down/complex.js' to match /^http:\/\/localhost:63342/
  at Assertion.assertMatch  <__intern/browser_modules/chai/chai.js:1363:10>
  at Assertion.ctx.(anonymous function) [as match]  <__intern/browser_modules/chai/chai.js:4192:25>
  at Test.test  <test/_private/utilTest.js:750:31>
  at <__intern/lib/Test.js:191:24>
  at <__intern/browser_modules/dojo/Promise.js:156:41>
  at runCallbacks  <__intern/browser_modules/dojo/Promise.js:19:22>
  at <__intern/browser_modules/dojo/Promise.js:103:21>
  at run  <__intern/browser_modules/dojo/Promise.js:51:33>
  at CallbackQueue.drain  <__intern/browser_modules/dojo/CallbackQueue.js:39:35>
  at MutationObserver.<anonymous>  <__intern/browser_modules/dojo/nextTick.js:52:27>
× chrome 57 on WIN8 - unit tests - _private/util - #browserModuleLocation - returns a sensible result with AMD module URI "/dir/dir/deep.js"
AssertionError: expected 'http://localhost:9000/dir/dir/deep.js' to match /^http:\/\/localhost:63342/
  at Assertion.assertMatch  <__intern/browser_modules/chai/chai.js:1363:10>
  at Assertion.ctx.(anonymous function) [as match]  <__intern/browser_modules/chai/chai.js:4192:25>
  at Test.test  <test/_private/utilTest.js:750:31>
  at <__intern/lib/Test.js:191:24>
  at <__intern/browser_modules/dojo/Promise.js:156:41>
  at runCallbacks  <__intern/browser_modules/dojo/Promise.js:19:22>
  at <__intern/browser_modules/dojo/Promise.js:103:21>
  at run  <__intern/browser_modules/dojo/Promise.js:51:33>
  at CallbackQueue.drain  <__intern/browser_modules/dojo/CallbackQueue.js:39:35>
  at MutationObserver.<anonymous>  <__intern/browser_modules/dojo/nextTick.js:52:27>

test/intern
Tunnel: Starting

Total: Pending
Passed: 1  Failed: 7  Skipped: 0

Chr 57 WIN: Pending, 7 fail

---------------------------------|----------|----------|----------|----------|----------------|
File                             |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
---------------------------------|----------|----------|----------|----------|----------------|
 I/                              |     92.2 |    77.69 |    91.74 |    93.81 |                |
  AbstractContract.js            |    96.63 |    91.43 |    96.43 |    97.18 |          25,26 |
  ConditionError.js              |    91.67 |     62.5 |    90.91 |    93.75 |          25,26 |
  ConditionMetaError.js          |    89.29 |       70 |       90 |    91.67 |          25,26 |
  ConditionViolation.js          |    93.62 |    83.33 |    94.44 |    94.59 |          25,26 |
  Contract.js                    |    93.48 |       85 |    90.91 |       95 |          26,27 |
  ContractError.js               |    88.46 |       50 |       80 |       92 |          25,26 |
  ExceptionConditionViolation.js |    88.89 |     62.5 |    88.89 |     91.3 |          25,26 |
  PostconditionViolation.js      |    88.89 |     62.5 |    88.89 |     91.3 |          25,26 |
  PreconditionViolation.js       |       85 |     62.5 |     87.5 |     87.5 |          25,26 |
 _private/                       |    93.88 |    80.41 |    97.37 |    93.85 |                |
  util.js                        |    93.88 |    80.41 |    97.37 |    93.85 |... 415,416,419 |
---------------------------------|----------|----------|----------|----------|----------------|
All files                        |     92.7 |     78.9 |     93.2 |    93.82 |                |
---------------------------------|----------|----------|----------|----------|----------------|